print('Geronimo Monsale')
print('Lupac,Boac,Marinduque')
print('March 12, 1999')
print('MAinduque State Collage')
print('Information Technology')
print('2C')
print('Playing Basketball')
print('Playing Volleyball')
print('Playing Chess')
print('Playing Online Games')
print('Playing Online Sabong')